version: '2'

services:
    catalogue:
        build:
            context: .
            dockerfile: ./docker/catalogue/Dockerfile
        image: neotysdevopsdemo/catalogue:TAG_TO_REPLACE
        hostname: catalogue
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
			- DT_CUSTOM_PROP=app=catalogue,environment=dev
        ports:
            - "8080:80"
    catalogue-db:
        build:
            context: ./docker/catalogue-db/
        image: neotysdevopsdemo/catalogue-db:TAG_TO_REPLACE
        hostname: catalogue-db
        restart: always
        environment:
            - reschedule=on-node-failure
			- DT_CUSTOM_PROP=app=catalogue-db,environment=dev
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
